### ISSUE TITLE
Version in DC/OS catalog - TAG is set to 0.7.1 instead of 0.7.2

### ISSUE THREAD

**Issue by jpopol** [deric/dcos-cerebro#1]
Hi
I just installed Cerebro from the catalog.
I had to change a tag for the health check to find the binary path, dependent on the version.

in the DC/OS catalog the version available for install is 0.7.2 but within the marathon definition we can see the Cerebro version tag set to 0.7.1

Not sure this is the right place to flag the issue. But hope it helps
Cheers
JP

**Comment by deric** [comment]
Hi, thanks for reporting that. It's just a string version, that shouldn't have any effect on functionality. Until it's fixed in the Universe, you can simply update version in Marathon definition.

**Comment by jpopol** [comment]
Yeah that's what I've done.
The only thing is that it crash health checking because binary
"./cerebro/0.7.1/..." can't be found and then cerebro never come up

2018-04-09 15:50 GMT+02:00 Tomas Barton <notifications@github.com>:

**Comment by a-nldisr** [comment]
Correct, the service crashes due to this:
```
I0807 12:40:08.787101     7 executor.cpp:478] Running '/opt/mesosphere/active/mesos/libexec/mesos/mesos-containerizer launch <POSSIBLY-SENSITIVE-DATA>'
I0807 12:40:08.788480     7 executor.cpp:651] Forked command at 12
sh: ./cerebro-0.7.1/bin/cerebro: No such file or directory
I0807 12:40:08.872782     8 executor.cpp:938] Command exited with status 127 (pid: 12)
```

**Comment by a-nldisr** [comment]
Created a pull request in the Universe repo:
https://github.com/mesosphere/universe/pull/1945

**Comment by a-nldisr** [comment]
This issue is fixed now, missed the existing pull request.
